server:
  servlet:
    contextPath: /localiza-drone

drone:
  lat: 0
  lng: 0

google:
  key: AIzaSyBRFjFVJA63W85SD85Ij3bdY1mRLOB8DE0
  src: https://maps.googleapis.com/maps/api/js?key=%s&callback=initMap&libraries=&v=weekly
